[connections.snowflake]
account = "TFTIJAU-NMB00862"
user = "jlrp69"
password = "JoseLuisSnowFlake1!"
private_key_file = "../xxx/xxx.p8"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
